//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_EST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification_Tab
    {
        public int Qualification_id { get; set; }
        public int Student_id { get; set; }
        public string CourseName { get; set; }
        public string University { get; set; }
        public int YearOfPassing { get; set; }
        public decimal Percentage { get; set; }
    }
}
