//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_EST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Std_Tab
    {
        public int Student_id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public int Age { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public long Phone_num { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
